#!/usr/bin/env node
/* Builds admin/payload.js: the Studio dashboard, encrypted at rest.
 *
 *   node scripts/admin-payload.js            encrypt scripts/admin-src -> admin/payload.js
 *   node scripts/admin-payload.js --check    decrypt the shipped payload and diff it
 *                                            against the sources (no writes)
 *   node scripts/admin-payload.js --pass X   use X instead of the local password file
 *
 * WHY THIS EXISTS. The repo is public and GitHub Pages serves every tracked
 * byte, so the admin surface is not shipped as markup: what ships is
 * AES-256-GCM ciphertext whose key is derived from the studio password by
 * 600,000 rounds of PBKDF2-SHA-256. The password lives in ONE place on this
 * machine, the .env.admin file at the repo root, which .gitignore's .env.*
 * rule keeps out of the repository; nothing derived from it (no hash, no
 * verifier) ships either, so there is nothing to attack but the KDF itself.
 * The gate in assets/js/admin-gate.js runs the same derivation in the
 * browser; GCM's tag is what tells a wrong password from a right one.
 *
 * The plaintext sources stay in scripts/admin-src/, which the deploy
 * workflow already strips from the artifact. They are ordinary UI code and
 * hold no secrets (the DATA is guarded by firestore.rules and the admin's
 * Firebase sign-in, not by obscurity); keeping them in the repo is what
 * lets the next session maintain the Studio. Run --check in the same breath
 * as build.js --check to catch an edited source nobody re-encrypted. */

"use strict";

const fs = require("fs");
const path = require("path");
const { webcrypto } = require("crypto");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(__dirname, "admin-src");
const OUT = path.join(ROOT, "admin", "payload.js");
const PASS_FILE = path.join(ROOT, ".env.admin");

const ITERATIONS = 600000;
const VERSION = 1;
const LOCK_AFTER_MINUTES = 15;
const USER = "admin";

function arg(name) {
  const i = process.argv.indexOf(name);
  return i === -1 ? null : process.argv[i + 1];
}

function readPassword() {
  const cli = arg("--pass");
  if (cli) return cli;
  if (process.env.ADMIN_PASS) return process.env.ADMIN_PASS;
  if (fs.existsSync(PASS_FILE)) {
    for (const line of fs.readFileSync(PASS_FILE, "utf8").split(/\r?\n/)) {
      const m = line.match(/^ADMIN_PASS=(.*)$/);
      if (m) return m[1];
    }
  }
  console.error(
    "No password. Put ADMIN_PASS=<password> in .env.admin at the repo root " +
      "(git ignores .env.*), or pass --pass / set ADMIN_PASS."
  );
  process.exit(1);
}

async function deriveKey(password, salt, usages) {
  const enc = new TextEncoder();
  /* "admin", a NUL, the password: the exact three pieces the gate encodes,
   * with the NUL built at runtime in both files on purpose. A raw zero
   * byte in a source string is invisible in a diff and turns the file
   * "binary" to every text tool, and the one time it happened it cost a
   * debugging session to see. */
  const material = await webcrypto.subtle.importKey(
    "raw",
    enc.encode(USER + String.fromCharCode(0) + password),
    "PBKDF2",
    false,
    ["deriveKey"]
  );
  return webcrypto.subtle.deriveKey(
    { name: "PBKDF2", hash: "SHA-256", salt, iterations: ITERATIONS },
    material,
    { name: "AES-GCM", length: 256 },
    false,
    usages
  );
}

const b64 = (buf) => Buffer.from(buf).toString("base64");
const unb64 = (s) => new Uint8Array(Buffer.from(s, "base64"));

function readSources() {
  return {
    html: fs.readFileSync(path.join(SRC, "dashboard.html"), "utf8"),
    code: fs.readFileSync(path.join(SRC, "dashboard.js"), "utf8"),
  };
}

async function build(password) {
  const enc = new TextEncoder();
  const salt = webcrypto.getRandomValues(new Uint8Array(16));
  const iv = webcrypto.getRandomValues(new Uint8Array(12));
  const key = await deriveKey(password, salt, ["encrypt"]);
  const plaintext = enc.encode(JSON.stringify(readSources()));
  const ciphertext = await webcrypto.subtle.encrypt(
    { name: "AES-GCM", iv, additionalData: enc.encode(`adriano-admin:v${VERSION}`) },
    key,
    plaintext
  );
  const out =
    "/* GENERATED by scripts/admin-payload.js. Do not edit: edit\n" +
    " * scripts/admin-src/ and rebuild. This is the Studio dashboard as\n" +
    " * AES-256-GCM ciphertext; the key never ships and is derived in the\n" +
    " * browser from the studio password (PBKDF2-SHA-256, " + ITERATIONS + " rounds).\n" +
    " * Without that password these bytes decode to nothing at all. */\n" +
    "window.ADRIANO_ADMIN_PAYLOAD = Object.freeze({\n" +
    `  version: ${VERSION},\n` +
    `  iterations: ${ITERATIONS},\n` +
    `  lockAfterMinutes: ${LOCK_AFTER_MINUTES},\n` +
    `  salt: "${b64(salt)}",\n` +
    `  iv: "${b64(iv)}",\n` +
    `  ciphertext:\n    "${b64(ciphertext).replace(/(.{96})/g, '$1" +\n    "')}",\n` +
    "});\n";
  fs.writeFileSync(OUT, out);
  console.log(
    `admin/payload.js written: ${plaintext.length} bytes of dashboard sealed ` +
      `under ${ITERATIONS} PBKDF2 rounds.`
  );
}

async function check(password) {
  if (!fs.existsSync(OUT)) {
    console.error("--check: admin/payload.js does not exist. Run the build first.");
    process.exit(1);
  }
  const src = fs.readFileSync(OUT, "utf8");
  const grab = (k) => {
    const m = src.match(new RegExp(`${k}:\\s*\\n?\\s*"([\\s\\S]*?)",`));
    if (!m) throw new Error(`--check: could not read ${k} out of payload.js`);
    return m[1].replace(/"\s*\+\s*\n\s*"/g, "");
  };
  const enc = new TextEncoder();
  const key = await deriveKey(password, unb64(grab("salt")), ["decrypt"]);
  let plain;
  try {
    plain = await webcrypto.subtle.decrypt(
      {
        name: "AES-GCM",
        iv: unb64(grab("iv")),
        additionalData: enc.encode(`adriano-admin:v${VERSION}`),
      },
      key,
      unb64(grab("ciphertext"))
    );
  } catch (e) {
    console.error(
      "--check: the shipped payload does not decrypt with the local password. " +
        "Either the password file changed or the payload is stale; rebuild it."
    );
    process.exit(1);
  }
  const shipped = JSON.parse(new TextDecoder().decode(plain));
  const sources = readSources();
  if (shipped.html !== sources.html || shipped.code !== sources.code) {
    console.error(
      "--check: scripts/admin-src/ has changed since admin/payload.js was " +
        "built. Run: node scripts/admin-payload.js"
    );
    process.exit(1);
  }
  console.log("admin/payload.js is current with scripts/admin-src/.");
}

const password = readPassword();
(process.argv.includes("--check") ? check(password) : build(password)).catch(
  (e) => {
    console.error(e);
    process.exit(1);
  }
);
